<?php

/**
 * @file
 * Contains acm_checkout.module.
 */

/**
 * Implements hook_theme().
 */
function acm_checkout_theme() {
  $theme = [
    'acm_checkout_progress' => [
      'variables' => [
        'steps' => [],
      ],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_user_logout().
 */
function acm_checkout_user_logout($account) {
  $cookies = \Drupal::request()->cookies->all();
  if (isset($cookies['Drupal_visitor_acm_order_id'])) {
    user_cookie_delete('acm_order_id');
  }
  if (isset($cookies['Drupal_visitor_acm_order_timestamp'])) {
    user_cookie_delete('acm_order_timestamp');
  }
}
