acm.currency:
  type: config_object
  label: 'Currency Settings'
  mapping:
    currency_code:
      type: label
      label: 'Currency Code'
    currency_code_position:
      type: label
      label: 'Currency Code Position'
    decimal_points:
      type: label
      label: 'Decimal Points'
    langcode:
      type: string
      label: 'Language code'
