acm_exception.settings:
  type: config_object
  label: 'API Exceptions'
  mapping:
    default:
      type: acm_exception_behavior
      label: Default exception handling
    routes:
      type: sequence
      label: API exception messages
      sequence:
        type: acm_exception_behavior

acm_exception_behavior:
  type: mapping
  label: Exception behavior
  mapping:
    message:
      type: text
      label: 'Message'
    redirect:
      type: string
      label: 'Redirect'
    log:
      type: integer
      label: 'Enable logging'
